global:
  scrape_interval: 5s
  evaluation_interval: 15s

rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "localhost:9090" ]

  - job_name: 'app'
    static_configs:
      - targets: [ 'app:8000' ]